cloudbase/garm

config/external.go, contrib/providers.d/azure/cloudconfig/install_runner.tpl, contrib/providers.d/azure/cloudconfig/userdata.tpl, contrib/providers.d/azure/config.sh, contrib/providers.d/azure/garm-external-provider, testdata/config.toml
* Fix more typos
* Add Azure external provider example
=> Add azure external provider

Dockerfile, Makefile
When /usr/bin/docker is a wrapper for podman (as common no Fedora),
Podman will be used which requires the full image name including the
registry. It does not require the chown step, because this results in
the files being owned by a temporary mapped ID due to the user
namespace in rootless mode (which is the default unless Podman is run
by the root user) - make the chown a no-op by using UID/GID 0.
=> Support building with Podman instead of Docker

config/config.go, config/config_test.go, config/testdata/test-empty-config-dir.toml, config/testdata/test-invalid-config.toml, config/testdata/test-valid-config.toml
* Fix NewConfig function
* Move the default setting before validating the config, otherwise the code will
never run. This happens because the `Validate()` function will always fail when
`config.Default.ConfigDir` is empty.
* Add unit tests for full coverage to the NewConfig function
=> Fix `NewConfig` func & and add more unit tests

params/params.go, params/requests.go, runner/interfaces.go, runner/organizations.go, runner/pool/organization.go, runner/pool/repository.go, runner/repositories.go, runner/runner.go
In order to allow mocking for some of the `runner` functions, we created a
separate interface (called `PoolManagerController`) with `Create`, `Get`,
`Delete` operations for the `organization` / `repository` pool managers.
Furthermore, a new runner struct (`poolManagerCtrl`) implements this new
interface. The existing code is refactored to use the `poolManagerCtrl`
whenever the pool managers for `org` / `repo` are handled.
This allows more unit testing for the runner functions since `poolManagerCtrl`
field can be mocked now.
Besides this, there are some typos fixed as well.
=> Refactor code to allow more unit testing

runner/repositories_test.go
Add more `repositories.go` unit testing
=> Add more `repositories.go` unit testing

database/sql/controller_test.go, runner/organizations_test.go, runner/repositories_test.go, util/tests_util.go
* Cleanup duplicate code
* Move `GetTestSqliteDBConfig` function to `util` package in order to eliminate duplicate code.
=> Cleanup duplicate code

database/sql/instances_test.go
=> Add `instances.go` unit tests

database/sql/instances.go, database/sql/instances_test.go, params/requests.go, runner/organizations_test.go, runner/pool/pool.go, runner/repositories_test.go
* Cleanup unused struct field
* Remove `Pool` field from `CreateInstanceParams` struct, because
this is given as a separate parameter to the `CreateInstance` function.
* Fix typo
=> Cleanup unused struct field and Fix typo

runner/common/util.go, runner/pool/interfaces.go, runner/pool/organization.go, runner/pool/pool.go, runner/pool/repository.go
In some cases, runner information is not sent via webhook by Github when a workflow job transitions to in_progress. We need to know the runner name in order to update the state in the database. Attempt to fetch the runner from the API using the workflow ID.
=> Attempt to fetch runner name from API

database/sql/instances_test.go, go.mod, go.sum, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/.gitignore, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/.travis.yml, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/LICENSE, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/README.md, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/argument.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/driver.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/expectations.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/expectations_before_go18.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/expectations_go18.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/result.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/rows.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/rows_go18.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/sqlmock.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/sqlmock_go18.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/statement.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/util.go, vendor/modules.txt
Add more test cases regarding the SQL database interactions.
Moreover, add `go-sqlmock` dependency used to mock SQL DB instructions.
=> Add `instances.go` database unit tests 

apiserver/controllers/controllers.go
This case is probably caused by a webhook event that was meant for another runner controller / manager. No need to report this as error, we can simply ignore this and avoid noise in the logs.
</sub>
=> feat: webhook does not return error on 'instance not found'.

database/sql/organizations.go
The error is not wrapped correctly, because instead of using `q.Error`, it uses `err`, which is defined elsewhere.
Also, the `UpdateOrganization` and `CreateOrganizationPool` functions will never fail on update/create org, because it returns a nil error, instead of wrap error.
=> Fixed error wrap

database/sql/pools_test.go
Add full tests coverage for `database/sql/pools.go` file.
=> Add `pools.go` database unit tests

database/sql/repositories_test.go
Add initial unit tests for the `database/sql/repositories.go` from `sql`package.
=> Add `repositories.go` unit testing

runner/pool/pool.go
When garm starts up, it attempts to cleanup any orphaned runners from github. This, unfortunately ends up deleting manually set up runners. This change looks for our controller ID in the labels of the runners and only deleted runners that we created.
Fixes: #40
=> Don't remove foreign runners

contrib/providers.d/azure/cloudconfig/install_runner.tpl, contrib/providers.d/openstack/cloudconfig/install_runner.tpl, contrib/providers.d/openstack/garm-external-provider
* The `{{ .RunnerUsername }}` is not replaced in any external providers' scripts.
However, we can safely assume that the username is properly created by cloud-init before the userdata is executed.
* Correctly use the `OS_TO_GH_ARCH_MAP` bash map.
Signed-off-by: Ionut Balutoiu <ibalutoiu@cloudbasesolutions.com>
=> Fix azure and openstack external providers

apiserver/controllers/controllers.go, apiserver/routers/routers.go, cmd/garm-cli/cmd/log.go, cmd/garm/main.go, config/config.go, go.mod, runner/runner.go, testdata/config.toml, websocket/client.go, websocket/websocket.go
This is a quality of life change that allows the operator to stream logs via web sockets. To enable this feature, you'll need to add:
```toml
[default]
enable_log_streamer = true
```
to your config file and restart garm.
After that, you can stream logs using ```garm-cli debug-log```:
```bash
ubuntu@garm:/tmp$ garm-cli debug-log
2022/10/21 08:41:41 connecting to wss://webhooks.samfira.com/api/v1/ws
2022/10/21 08:41:41 10.198.117.1 - - [21/Oct/2022:08:41:41 +0000] "GET /api/v1/ws HTTP/1.1" 200 0 "" "Go-http-client/1.1"
2022/10/21 08:43:39 10.198.117.1 - - [21/Oct/2022:08:43:39 +0000] "GET /api/v1/instances HTTP/1.0" 200 773 "" "go-resty/2.7.0 (https://github.com/go-resty/resty)"
```
=> Add log streamer

cmd/garm/main.go, runner/pool/enterprise.go, runner/pool/organization.go, runner/pool/pool.go, runner/pool/repository.go, runner/runner.go
* Wait for http server graceful shutdown and for pool managers to properly exit.
* Fix potential nil pointer dereference when checking response code from github API.
=> Wait for loop exit and some fixes

contrib/providers.d/azure/garm-external-provider, contrib/providers.d/openstack/garm-external-provider, doc/external_provider.md, runner/pool/pool.go
* Ensure the pool loop exits properly when the pool is not yet in a running state.
* Use ListInstances() when cleaning orphaned runners. This ensures We only run one API call per pool to list instances, instead of running a GetInstance() for each individual instance we are checking.
=> Ensure loop closes properly and provider update

runner/common/pool.go, runner/pool/pool.go
This automatically scales down superfluous runners.
There are a number of scenarios where we end up with more runners than the idle pool size.
E.g. when you change the min_pool_size ..
This PR is an example of how we could scale down runners that are not needed at the moment.
What do you think? 
The runners are deleted not all at once but each `PoolScaleDownInterval` half of the surplus is deleted until we hit `min_idle_runners`
So far, neither the Iterval (1 Minute) nor the percentage of runners to be removed is configurable.
</sub>
=> feat: scale down idle runners

runner/pool/pool.go
Sorry...
I committed some un-tested idea where I wanted to remove the ugly '-' and '_' in the shortid.
It doesn't work like that, and currently the runner name generation is broken!
</sub>
=> fix: shortid generates correctly now

auth/instance_middleware.go, params/params.go, runner/common/pool.go, runner/pool/pool.go
The ```Scope``` field is not really used, but we may need it later.
=> Move pool type in params

README.md, doc/database.md, doc/external_provider.md, doc/github_credentials.md, doc/providers.md, doc/running_garm.md, doc/webhooks_and_callbacks.md, go.mod
Hello,
- While reading docs, I've noticed some small mistakes that could be easily fixed using markdown or a spell check.
- Also while trying to check the project, go extension complained about `shortid` which was fixed by running `go mod tidy`.
Thanks,
Ionut
=> Markdown lint

Makefile, scripts/build-static.sh
Removes windows as a target to build binaries for.
=> Disable Windows binary build

database/sql/enterprise.go, database/sql/enterprise_test.go, database/sql/organizations.go, database/sql/organizations_test.go, database/sql/repositories.go, database/sql/repositories_test.go, database/sql/util.go, errors/errors.go, params/requests.go, runner/enterprises_test.go, runner/organizations_test.go, runner/repositories_test.go, runner/runner.go
Webhooks seemed never to be validated (see behaviour for empty secret in [runner.go#L544-547](https://github.com/cloudbase/garm/blob/main/runner/runner.go#L544-547)) as the secret of the enterprises and orgs were not properly set (see [enterprise.go#L73-L86](https://github.com/cloudbase/garm/blob/main/database/sql/enterprise.go#L73-L86), [organizations.go#L71-L84](https://github.com/cloudbase/garm/blob/main/database/sql/organizations.go#L71-L84)). For repos the feature seems to work as expected.
**Essentially we need to decide whether empty secrets can be set to disable the validation or not**. After we decided on that I would update the PR accordingly.
* so far I only fixed the code for enterprises after we decided whether we allow for empty secrets  I will fix the code for …
=> Fix webhook signature validation

database/sql/util.go
Bug:
the runner prefix is always overwritten. Even if I only want to update e.g. max-runners. If the runner prefix is not specified the default value will be used
Fix:
Only update runner prefix if a value was set.  
</sub>
=> fix: don't update empty runner prefix

apiserver/controllers/controllers.go, apiserver/routers/routers.go, cmd/garm-cli/cmd/repo_pool.go, cmd/garm/main.go, metrics/metrics.go, runner/pool/pool.go, runner/runner.go, testdata/config.toml, util/util.go
This change is just a couple of small fixes and moving some code around.
* metrics are moved to its own package
* the short ID is sanitized to replace hyphens and dashes with alphanumeric characters
* the runner prefix is now displayed properly in pool show
=> Move some code around

runner/pool/pool.go
If we fail to cleanup failed instance, we return before retrying to recreate it.
Fixes: #76 
=> Bail if we fail to cleanup failed instance

runner/pool/pool.go
Add a grace period for idle runners of 5 minutes. A new idle runner will not be taken into consideration for scale-down unless it's older than 5 minutes. This should prevent situations where the scaleDown() routine that runs every minute will evaluate candidates for reaping and erroneously count the new one as well. The in_progress hooks that transitiones an idle runner to "active" may arive a long while after the "queued" hook has spun up a runner.
=> Add grace period to scale-down

cloudconfig/cloudconfig.go, cmd/garm-cli/cmd/pool.go, cmd/garm/main.go, config/config.go, config/config_test.go, database/sql/models.go, params/params.go, params/requests.go, runner/enterprises.go, runner/organizations.go, runner/providers/external/external.go, runner/providers/lxd/lxd.go, runner/providers/lxd/util.go, runner/providers/providers.go, runner/repositories.go, runner/types.go, util/appdefaults/appdefaults.go, util/util.go
The params package should not depend on config. The params packages should be consumable by external applications that wish to interact with garm, and it makes no sense to pull in the config package just for some constants. As such, the following changes have been made:
* Moved some types from config to params
* Moved defaults in a new leaf package called appdefaults
=> Move some defaults and types from config

cloudconfig/templates.go
I'm trying your new garm-provider-openstack. So far it's looking good. But we don't have some long time numbers yet.
I wanted to discuss this little idea that could save us some time.. 
For green IT reasons we've already pre-installed the github runner in our runner images. Hence, no need to install it during boot/cloud-init. This PR shows a quick check if the runner dir is already there. Probably this check should be a little bit more robust.. What do you think?
This saves us thousands of downloads and installs .. 
I also added the `curl -k` as we currently do need this in our test pipeline and I believe in the bash provider you also had the `-k` added to the curl requests.
=> check if runner needs to be installed

params/params.go, util/util.go
Allow to disable an package updates during boot / cloud-init by adding a new field `UserDataOptions` to `BootstrapInstance` parameters.
This does not change the signature of func `GetCloudConfig`. The default behavior does not change.
=> Add Userdata options to disable package update during boot / cloud-init

runner/providers/lxd/lxd.go
We should be looking for the poolIDKey in the extended LXD config. This was an unfortunate typo. Unit an integration tests will be added in the medium term.
=> Fix pool ID check when listing instances

cloudconfig/templates.go, runner/providers/lxd/images.go, runner/providers/lxd/lxd.go
If we give ```CreateInstance()``` a remote image as a source, it will automatically download the image and cache it locally. If configured, LXD will also auto update the image periodically. Using ```CopyImage()``` gives us none of this.
This change removes the ```CopyImage()``` code and allows ```CreateImage()``` to do the right thing.
=> Let CreateInstance download and cache image

runner/providers/lxd/lxd.go, runner/providers/lxd/specs.go
This change allows disabling updates via extra specs in the LXD provider.
To disable updates, add the following extra specs
```bash
garm-cli pool update \
--extra-specs='{"disable_updates": true}' \
<POOL_ID>
```
Fixes: https://github.com/cloudbase/garm/issues/93
=> Allow disabling updates

go.mod, go.sum, runner/pool/pool.go, runner/providers/lxd/lxd.go, vendor/golang.org/x/sync/LICENSE, vendor/golang.org/x/sync/PATENTS, vendor/golang.org/x/sync/errgroup/errgroup.go, vendor/modules.txt
* cleanupOrphanedGithubRunners() now uses errgroup to parallelize and report errors when removing runners from the provider.
* retryFailedInstancesForOnePool() now uses errgroup
* Removed some setPoolRunningState which should be treated in the loop where those errors eventually bubble up and can be handled.
* Added a number of timeouts in the LXD provider for delete and list instances. This provider should be converted into an external provider.
=> Parallelization and LXD timeouts

cmd/garm-cli/cmd/enterprise.go, cmd/garm-cli/cmd/organization.go, cmd/garm-cli/cmd/pool.go, cmd/garm-cli/cmd/repository.go
The second column that is printed when showing a resource, contains values that should not be merged, even if they are similar.
Fixes: https://github.com/cloudbase/garm/issues/100
=> Don't merge the second column in the CLI

runner/providers/common/common.go, runner/providers/external/external.go, scripts/build-static.sh
Providers may return only 3 possible statuses:
* InstanceRunning
* InstanceError
* InstanceStopped
Every other status is reserved for the controller to set. Provider responses will be split from the instance response in a future commit.
=> Validate provider responses

params/params.go, runner/providers/lxd/lxd.go, runner/providers/lxd/specs.go, util/util.go
Dear maintainers,
This proposed change extends the `UserDataOptions` introduced in #87 and #95 so that the user can configure additional packages to be installed into the runner of each pool. 
This can be very useful when GitHub Actions workflows require Docker to be installed in the runner. This can be configured via
```bash
garm-cli pool update \
--extra-specs='{"extra_packages": ["docker.io"]}' \
<pool id>
```
=> Allow installing additional packages in lxd container

database/sql/users_test.go
* Add more coverage for the `users.go` using the SQL database interactions.
=> Add more test cases for the `/database/sql/users.go`

Makefile, cloudconfig/templates.go, runner/pool/pool.go
This change reaps runners that appear as `offline` in github and have their `RUNNER STATUS` set to `failed`. Runners that are in this state have registered themselves in GutHub, but failed at a later stage in the setup process. We reap them if no new updates have been made to the instance after the configured pool timeout.
This change also adds a retry when running `config.sh` via userdata. Hopefully in future releases we can switch to using [jit runners](https://github.blog/changelog/2023-06-02-github-actions-just-in-time-self-hosted-runners/) but for the time being, this is not available for GHE.
Fixes: https://github.com/cloudbase/garm/issues/104
=> Reap failed agent

cloudconfig/templates.go, util/util.go
This change executes the runner install script provided via userdata using su. The script itself has also been changed to assume it's running as the runner user.
Fixes: #113
=> Use su to install the runner

cmd/garm/main.go, contrib/garm.service, doc/logging.md
Fixes https://github.com/cloudbase/garm/issues/114.
Add functionality to rotate the log file when `SIGHUP` signal is received.
Also, a doc is added with few details about logging.
=> Rotate log file on SIGHUP

runner/pool/pool.go, runner/pool/util.go
* removes an extra loop. The fetch tools loop does the same job
* add a lot of log messages
* Make sure Unlock() is always called and is called only once
=> Add logging and fix backoff loop

runner/pool/pool.go
=> Update comment on function

.github/workflows/build-and-push.yml, Dockerfile, Dockerfile.build-static, Makefile, scripts/build-static.sh
This PR adds:
* `make build-static` now builds ARM64 binaries as well
* A Dockerfile was added to build garm and the currently available providers
* A new workflow was added to build the image and upload it to ghcr.io
=> Add dockerfile and workflow

apiserver/routers/routers.go, auth/jwt.go
* Fix `Content-Type` not being set on `invalidAuthResponse`
* Fixes https://github.com/cloudbase/garm/issues/137
* Fix calling `/api/v1/first-run` API endpoint without ending `/`
=> Small fixes to the GARM api server

doc/config_default.md, doc/external_provider.md, doc/quickstart.md, go.mod, go.sum, runner/providers/lxd/lxd.go, runner/providers/lxd/specs.go, testdata/config.toml, vendor/github.com/cloudbase/garm-provider-common/cloudconfig/templates.go, vendor/modules.txt
Using the latest version of `garm-provider-common` we can finally consolidate the way we define the `callback_url` with the `metadata_url`. Also updated the docs to point to the latest release.
Using the old callback_url that points to the URL ending in `/status` will continue to work.
Fixes: #88
=> Update to latest version of garm-provider-common and update docs

.github/workflows/integration-tests.yml, test/integration/config/config.toml, test/integration/e2e.go, test/integration/scripts/setup-garm.sh
* This PR adds `GitHub workflow` that runs `integration tests`.
* The steps in the integration tests are:
*  `Setup Golang`
*  `Setup LXD`
*  `Build GARM`
*  `Setup GARM `
*  `Generate secrets`
*  `Setup ngrok`
*  `Run integration tests`
*  `Show GARM logs`
=> Add GitHub workflow for integration tests

.github/workflows/integration-tests.yml, test/integration/e2e.go
* This PR adds `upload artifacts` for `Github Actions` and log `instance` details on timeout exceeded.
=> Add upload artifacts and log instance details on timeout exceeded

.github/workflows/integration-tests.yml, test/integration/e2e.go
* This PR adds log `org/repo` details on timeout exceeded and `set -o pipefail` option to the script.
=> Set pipefail to the script and log org/repo details on timeout exceeded

.github/workflows/integration-tests.yml, test/integration/e2e.go
* This PR implements cleanup of the `orphan runners` for `org/repo`.
* I updated the PR with the following changes:
* I replaced the `log.Fatalf` with `panic` to prevent the `exit 1` from interrupting the defer statement.
* I put `graceful cleanup functions` in a function called `GracefulCleanup` and deferred it first.
* Make sure that the `graceful cleanup functions` are idempotent.
* I also added two functions: (`GhOrgRunnersCleanup` and `GhRepoRunnersCleanup`) to forcefully delete the runners via  `GitHub API` and deferred them after the `GracefulCleanup` function.
=> Cleaning up leftover runners for `org/repo`

test/integration/e2e.go
If everything is fine, we return early from the `Wait` functions. 
Just breaking the loop executes the code following the loop, which is meant to be executed only on timeout exceeded.
=> Fix timeout logic

doc/database.md, doc/quickstart.md
* This PR update the following in the GARM docs:
* `doc/database.md` --> The `passphrase` needs to have 32 characters.
* `doc/quickstart.md` --> Correct the incorrect URL for `database.md`.
=> Small fixes for the docs

.github/workflows/integration-tests.yml
Some integration tests workflows failed with:
```
Error: Invalid format 'ORG_WEBHOOK_SECRET=***'
```
or
```
Error: Invalid format 'GARM_PASSWORD=***'
```
Workflow runs logs:
* https://github.com/cloudbase/garm/actions/runs/5920389694/job/16051606203#step:7:26
* https://github.com/cloudbase/garm/actions/runs/5908193226/job/16027297143#step:7:26
This is a transient error, as it only happens sometimes.
I suspect that sometimes there is some illegal sequence of characters
in the random generated strings. Thus, the GitHub actions logic to
parse the environment fails.
This change removes the special characters that would have a special
meaning in bash, from the `randomStringGenerator` function, in hopes
to fix the transient issue.
Also, silence `try` stderr messages, and fix spacing in the …
=> Fix e2e secrets generation

.github/workflows/integration-tests.yml, test/integration/config/config.toml, test/integration/e2e.go, test/integration/scripts/setup-garm.sh
This PR implements the following changes:
* Get `controller info`
* `Install/get` webhooks for `org` and `repo`.
* Trigger a `workflow test` with a specific `label name`.
* Validate the job lifecycle with the following steps:
* ensure the job is recorded in the job list.
* ensure the job goes through `queued` and `in_progress` stages.
* ensure the job runner instance is running and active.
* ensure the job is completed.
* ensure the runner instance is removed.
* wait for GARM to rebuild pool running idle instances after the job is done.
=> Add webhooks integration tests for `organization` and `repository`

.github/workflows/integration-tests.yml
It appears that in some cases, generating passwords by reading /dev/urandom and piping to tr, fails. Use apg.
=> Use apg to generate passwords

cmd/garm-cli/cmd/pool.go, cmd/garm-cli/cmd/runner.go
If for whatever reason the list API call failed, `response` would have been `nil`. That means that trying to access `response.Payload` would have resulted in a nil pointer dereference.
CC @mihaelabalutoiu
=> Fix nil pointer dereference

util/util.go
The CA bundle must be set on RootCAs to properly validate the remote server.
=> Fix TLS client bug

runner/pool/pool.go
If we fail to get the tools for one pool, garm fails to start due to pool manager startup timeout. Launch the initial tools update function as a goroutine and return from Start(). If it fails, it will retry, and we won't block garm from starting.
=> Fix garm pool manager startup

database/sql/enterprise.go, database/sql/organizations.go, database/sql/repositories.go
The github runner group was not being set during pool creation. this change fixes that.
=> Properly set runner group when creating a pool

test/integration/e2e/instances.go
Instead of asking for all the GARM instances from the API, and then filtering them by `poolID`, we can ask the API to return only the instances that are in the `poolID` pool.
Therefore, we only need to count the instances that are running and idle.
=> Optimize `waitPoolRunningIdleInstances` func

database/sql/instances_test.go, database/sql/jobs.go, database/sql/models.go, database/sql/sql.go, runner/common/mocks/GithubClient.go, runner/common/mocks/OrganizationHooks.go, runner/common/mocks/RepositoryHooks.go
GARM relies on a combination of webhook events and polling to function properly. While most times we will successfully receive webhooks, in some cases we may miss some. Be it because we were offline or because GitHub is having an issue.
When it comes to runners, we periodically check for orphaned runners and clean them up. For Jobs on the other hand, we only check those that are in `queued` state, under certain circumstances. Once they transition to any other state (other than `completed` or `queued`), we don't really check them any more.
Jobs that transition to `in_progress` will generally have a runner associated. This change adds a foreign key constraint between the runner (if found) and the job. We also set an `on delete cascade` constraint on that foreign key. 
This will ensure that …
=> Add relation to jobs

apiserver/controllers/instances.go, apiserver/controllers/metadata.go, apiserver/routers/routers.go, auth/context.go, params/params.go, runner/common/mocks/PoolManager.go, runner/common/pool.go, runner/metadata.go, runner/pool/pool.go
Thic change adds a metadata endpoint that returns a list of root CA certificates a runner must install in order to be able to validate all relevant API endpoints it may require. This includes any GHES API that runs on a self signed certificate.
=> Add root CA bundle metadata URL

test/integration/e2e/client_utils.go, test/integration/e2e/github_client_utils.go, test/integration/e2e/organizations.go, test/integration/e2e/repositories.go, test/integration/gh_cleanup/main.go, test/integration/main.go
This PR adds the following changes:
* A method to remove the `orphan webhooks` for `org/repo`. This is useful, if the `uninstall` of the webhooks failed.
* A further check on the Github webhooks state after `install/uninstall` logic.
=> Cleaning up leftover Github webhooks for `org/repo`

doc/config_metrics.md, metrics/enterprise.go, metrics/health.go, metrics/instance.go, metrics/metrics.go, metrics/organization.go, metrics/pool.go, metrics/provider.go, metrics/repository.go, metrics/util.go
add info metrics about providers, enterprises, organizations, repositories and pools.
Also expose most of the configurable pool information as metric like e.g. max Runners as garm_pool_max_runners
=> feat: add new metrics

config/config.go, runner/common/mocks/Provider.go, runner/common/provider.go, runner/pool/pool.go, runner/providers/external/external.go, runner/providers/lxd/lxd.go, testdata/config.toml
This change adds a flag on providers that allows users to disable JIT configuration even when it's available. For context, JIT is available on github.com and any GHES instance >=3.10.
This option is a stopgap measure for providers that have not yet been updated to use JIT configs instead of runner registration tokens.
=> Add option to disable JIT config

README.md
=> Add some more info to README

params/params.go, runner/pool/pool.go
On large deployments with many jobs, we cannot check each job that we recorded in the DB against the GH API.
Before this change, if a job was updated more than 10 minutes ago, garm would check against the GH api if that job still existed. While this approach allowed us to maintain a consistent view over which jobs still exist and which are stale, it had the potential of spamming the GH API, leading to rate limiting.
This change uses the scale-down loop as an indicator for job staleness.
If a job remains in queued state in our DB, but has dissapeared from GH or was serviced by another runner and we never got the hook (garm was down or GH had an issue - happened in the past), then garm will spin up a new runner for it. If that runner or any other runner is scaled down, we check if we have …
=> Prevent abusing the GH API

test/integration/scripts/setup-garm.sh
We need to export the variables before they can be used with envsubst.
=> Export required variables

apiserver/controllers/instances.go, apiserver/routers/routers.go, params/params.go, params/requests.go, runner/runner.go
Allow runners to update their own system information. The goal is to get better info about the runners that we spawn. Right now we just retrieve os_name, os_version and agent_id, but this can be expanded later to include other info.
We also want to collect the actual agent_id of the GH runner using a callback that makes more sense. The status updates should only report installation status, which is informational.
=> Add system-info instance callback

cmd/garm-cli/cmd/log.go, cmd/garm/main.go, websocket/websocket.go
I accidentally disabled the log streamer when I moved the config options to their own section. This change fixes that.
This change also adds some safety checks and locking when cleaning up stale clients. The websocket hub Write() function now copies the message before sending it on the channel to the clients.
=> Fix log streamer and cleanup code

runner/common/pool.go, runner/providers/external/external.go, runner/runner.go, websocket/websocket.go
This change increases the tools refresh interval to 5 minutes, cleans up the websocket code a bit, augments the error message that may be returned when trying to delete a runner in an invalid state and removes a log message that does not add much value.
=> Small adjustments

runner/pool/pool.go
Adds some extra logging and context.
=> Add some logging

auth/instance_middleware.go
This change invalidates tokens based on more parameters. Tokens that were generated for previous attempts of spinning up an instance will be invalidates.
Also, only instances that are in Running or Creating will be able to authenticate.
=> More strict instance token checks

README.md, doc/providers.md, doc/quickstart.md
=> Add GCP to the list of providers

cmd/garm-cli/cmd/enterprise.go, cmd/garm-cli/cmd/pool.go
This change:
* Removes the `--random-webhook-secret` option from enterprises
* Fixed some help typos
=> Fix typos in garm-cli

Dockerfile
Without '-linkmode external' some of the produced binaries were not actually static. /bin/garm was fine but providers would fail with "exit code 127" when executed. Unpacking the container image and running the binaries in strace showed that they were accessing the musl dynamic linker.
=> Dockerfile: Build actually static binaries

Makefile, test/integration/config/config.toml, test/integration/e2e/e2e.go, test/integration/e2e/instances.go, test/integration/e2e/repositories.go, test/integration/main.go, test/integration/scripts/setup-garm.sh
This change adds the ability to run integration tests locally. You will still need a number of environment variables set, including a github PAT.
Details on how to use this will come in a subsequent commit.
=> Allow integration tests to run locally

.github/workflows/integration-tests.yml, Makefile
Install make dependencies and default to current user
=> Install dependencies and set RUN_USER

.github/workflows/integration-tests.yml, test/integration/config/config.toml, test/integration/scripts/setup-garm.sh
In hindsight this should have been fixed in a private fork and pushed instead of creating multiple PRs. Maybe next time :sweat_smile: .
=> Fix variable name

cmd/garm-cli/cmd/runner.go, database/sql/enterprise.go, database/sql/instances.go, database/sql/organizations.go, database/sql/repositories.go, database/sql/util.go, params/params.go, runner/metrics/metrics.go, runner/pool/pool.go
This change adds information about the job a runner is currently handling.
This change also adds a new flag to the CLI `--long | -l` to display this info.
Fixes #184
=> Add job info in runner list

runner/pool/pool.go, util/util.go
When no runner group is set, do not attempt to resolve the runner group. Looking for an empty runner group will just return a not found error, which will make GARM fall back to registration token.
This change fixes that.
=> Fix JIT config with empty runner group name

cmd/garm-cli/cmd/log.go
There was a nil pointer dereference when an error was returned by the log streamer API. This change fixes that.
=> Check for nil pointer before dereferencing

cmd/garm-cli/cmd/pool.go
This change fixes a potential nil pointer dereference when a call to create a pool, fails.
=> Fix potential nil pointer dereference in cli

database/common/common.go, database/common/mocks/Store.go, database/sql/enterprise.go, database/sql/enterprise_test.go, database/sql/instances.go, database/sql/instances_test.go, database/sql/organizations.go, database/sql/organizations_test.go, database/sql/pools.go, database/sql/pools_test.go, database/sql/repositories.go, database/sql/repositories_test.go, database/sql/util.go, params/params.go, runner/enterprises.go, runner/enterprises_test.go, runner/organizations.go, runner/organizations_test.go, runner/pool/pool.go, runner/pools.go, runner/pools_test.go, runner/repositories.go, runner/repositories_test.go, runner/runner.go
This change aims to simplify the DB code a bit and optimize the queries.
=> Deduplicate db code

database/common/common.go, database/common/mocks/Store.go, database/sql/instances.go, database/sql/instances_test.go, runner/metadata.go, runner/pool/pool.go, runner/runner.go
Change instance DB functions from querying by ID to querying by name. Names are unique in GARM, so we might as well use the name instead of the ID and spare ourselves the extra query to get the ID when a qorkflow comes in.
This change also removes an unused function.
=> Slightly simplify code

runner/pool/locking.go, runner/pool/pool.go, runner/pool/util.go
Remove code that was just wrapping other functions at this point, and move some code around. We need to get a better idea what is actually still needed in the pool manager, to begin to refactor it into something that can scale out.
=> Remove some code, move some code around

database/sql/enterprise_test.go, database/sql/organizations_test.go, database/sql/pools.go, database/sql/repositories.go, database/sql/repositories_test.go
This change removes a check that denies the creation of a pool if the new pool has the same image and flavor set on the same provider. The reasoning for that check was that if you need to create another pool with identical settings to an existing one, you might as well scale up the min-idle-runners on the old one.
This was done when runner groups were not yet added. This in turn has forced users to alias images with new names in their provider, leading to terrible UX. In the end, being too opinionated in this case has caused more harm than good.
Fixes #245
=> Remove check for duplicate pool

database/sql/enterprise_test.go, database/sql/instances_test.go, database/sql/organizations_test.go, database/sql/pools_test.go, database/sql/repositories_test.go, doc/external_provider.md, doc/labels.md, doc/quickstart.md, doc/using_garm.md, runner/enterprises_test.go, runner/organizations_test.go, runner/pools.go, runner/pools_test.go, runner/repositories_test.go, runner/runner.go
towards https://github.com/cloudbase/garm/issues/248
=> New runners without default labels

README.md
In a lot of cases, people will land on the repo README page and attempt to go through the docs to set  up GARM. The docs in the main branch may have instructions in regards to using functionality that is not yet released. As such, following the instructions may lead to errors and confusion.
This note will hopefully help and guide users to the docs released along with stable versions.
=> Add note about stable release documentation

runner/pool/pool.go
github is sending job events where conclusion=cancelled is spelled in american english.
=> fix: use the american english type of cancelled

runner/pool/pool.go
There are only a few cases, where we get a job information from github where the runner name is not set.
For all this cases we do not need to check github API at all because these jobs are never ever get scheduled to a runner:
job.Action is:
* queued: a queued job is just queued and not scheduled to a runner so we do not get a runner name from the GH API
* completed: when conclusion=cancelled|failure github never scheduled the job to a runner and with that we do not get a runner name from the GH API
=> fix: remove unnecessary github api call

README.md, cmd/garm/main.go, database/common/errors.go, database/common/store.go, database/common/watcher.go, database/sql/controller.go, database/sql/enterprise.go, database/sql/github.go, database/sql/instances.go, database/sql/jobs.go, database/sql/organizations.go, database/sql/pools.go, database/sql/repositories.go, database/sql/repositories_test.go, database/sql/sql.go, database/sql/util.go, database/watcher/consumer.go, database/watcher/filters.go, database/watcher/producer.go, database/watcher/test_export.go, database/watcher/watcher.go, database/watcher/watcher_store_test.go, database/watcher/watcher_test.go, internal/testing/mock_watcher.go, internal/testing/testing.go, runner/pool/pool.go, runner/repositories_test.go
Adds a database watcher framework that will allow us to react to changes made to entities in the database.
=> Add database watcher

runner/pool/pool.go
There is no reason to log this as error.
=> Lower the log level of ignored jobs

cmd/garm-cli/cmd/controller.go, cmd/garm-cli/cmd/init.go, database/sql/controller.go, database/sql/models.go, database/sql/sql.go, params/params.go, params/requests.go, runner/pool/pool.go
GARM has a backoff interval when consuming queued jobs. This backoff is intended to allow any potential idle runners to pick up a job before GARM attempts to spin up a new one. This change allows users to set a custom backoff interval or disable it altogether by setting it to 0.
Fixes: #270
=> Allow configuration of job backoff interval

Dockerfile, Makefile, cmd/garm-cli/cmd/controller.go, cmd/garm-cli/cmd/root.go, cmd/garm-cli/cmd/version.go, cmd/garm/main.go, database/sql/controller.go, params/params.go, scripts/build-static.sh, util/appdefaults/appdefaults.go
This change adds the GARM server version to the controller info response. It also amends the `version` sub-command to include the server version if available.
=> Add version to controller info response

doc/labels.md, doc/quickstart.md
This change removes a stray line in the quickstart and rewords the section about labels a bit.
=> Reword the section about labels

cmd/garm-cli/cmd/enterprise.go, cmd/garm-cli/cmd/organization.go, cmd/garm-cli/cmd/repository.go, database/common/store.go, database/sql/enterprise.go, database/sql/enterprise_test.go, database/sql/models.go, database/sql/organizations.go, database/sql/organizations_test.go, database/sql/repositories.go, database/sql/repositories_test.go, runner/enterprises.go, runner/enterprises_test.go, runner/organizations.go, runner/organizations_test.go, runner/pool/pool.go, runner/pool/watcher.go, runner/repositories.go, runner/repositories_test.go, runner/runner.go
This change scopes all github entities to a github endpoint, allowing users to have the same repo/org/enterprise created for each endpoint.
This way, if your username is the same on github.com and on your GHES server, and you have the same repository name or org in both places, GARM can now handle that situation.
This change also fixes a leaky watcher in the pool manager.
=> Fix: Scope entities to endpoint

cmd/garm-cli/cmd/events.go, cmd/garm-cli/cmd/log.go, cmd/garm-cli/common/common.go, websocket/util.go
This change adds a new message handler that users of the reader can use to handle websocket messages. Packages should never print to console by themselves.
=> Generalize the websocket reader

apiserver/routers/routers.go, cmd/garm-cli/cmd/events.go, cmd/garm-cli/cmd/log.go
Given that we now have multiple websocket URLs (logs and events), this change categorizes them under the same prefix.
=> Rename websocket URLs

apiserver/events/params.go, database/common/watcher.go
This change adds json tags to the ChangePayload struct, as this struct now gets marshaled into JSON by the events WS endpoint.
=> Add JSON tags to the ChangePayload struct

.github/workflows/integration-tests.yml
This change switches the integration tests to an alternate tunneling service.
=> Replace ngrok

.github/workflows/integration-tests.yml, test/integration/config/config.toml, test/integration/scripts/setup-garm.sh
GitHub hosted runners seem to have issues with LXD containers. In all likelihood, downloading images is slow and the tests end up timing out. This switches to self hosted runners, managed by GARM.
=> Switch to self hosted runner

.github/workflows/go-tests.yml, .github/workflows/integration-tests.yml, test/integration/config/garm-provider-lxd.toml, test/integration/external_provider_test.go, test/integration/organizations_test.go, test/integration/repositories_test.go, test/integration/scripts/setup-garm.sh
This change allows GARM tests to use a mirror for LXD images, allowing for faster image downloads.
=> Allow using LXD image mirror

database/sql/enterprise_test.go, database/sql/organizations_test.go, database/sql/pools.go, database/sql/repositories_test.go, database/sql/util.go
This change switches to a case insensitive search for pool tags.
Fixes: #295
=> Do a case insensitive search for tags

cmd/garm-cli/cmd/controller.go, cmd/garm-cli/cmd/enterprise.go, cmd/garm-cli/cmd/github_credentials.go, cmd/garm-cli/cmd/github_endpoints.go, cmd/garm-cli/cmd/jobs.go, cmd/garm-cli/cmd/organization.go, cmd/garm-cli/cmd/pool.go, cmd/garm-cli/cmd/profile.go, cmd/garm-cli/cmd/provider.go, cmd/garm-cli/cmd/repository.go, cmd/garm-cli/cmd/root.go, cmd/garm-cli/cmd/runner.go, cmd/garm-cli/common/cobra.go
This change adds a --format command line option to the GARM cli. This option accepts either json or table as a value.
=> Add --format command line option

cmd/garm-cli/cmd/root.go, cmd/garm-cli/common/cobra.go
This change properly adds a default value to the new `--format` option.
=> Add a default value to the new --format option

Dockerfile
The busybox image does not contain CA certificares. This adds them from the builder stage.
=> Copy the CA certificates to final image

runner/repositories.go, runner/repositories_test.go
The API code unwraps errors wrapped by the errors.Wrap() function. It falls back to 500 error if it can't determine any other error type.
Ultimately we need to migrate to the fmt.Errorf() pattern. But for now at least, we need to return proper errors. Any 500 error will not output details to the API. Neither will 401 for similar reasons.
=> Use errors.Wrap() in repositories.go

doc/using_cached_runners.md
- Adds documentation for using cached GitHub action runners for Windows and Linux
Not to be merged before the following PRs are merged:
=> Add Using Cached Runner documentation

.golangci.yml, Makefile, database/sql/jobs.go, database/sql/util.go, runner/pool/pool.go
finding errors in logs is very important and there are some logs that are `errors` but seem to be rather normal:
- workflow events without labels -> this happens very often (at least in our GHE instance), this might be a bug in github code .. but garm probably has to accept this and don't consider this an error
- workflows that have runner_names which are not `our` runners. This always happens in a scenario where our garm runners are not the only runner setup (and we still get the workflow_job events, e.g. enterprise wide hooks)
=> Improve error messages in garm log

runner/metadata.go
The User option in the systemd unit file used when JIT configs are enabled had a hardcoded value of "runner". This change fixes that oversight.
=> Fix hardcoded user value in template

apiserver/params/params.go, auth/init_required.go
Webhook URL was not mandatory in previous versions. While it is needed if users plan to use the install webhook feature, it is not required if you want to install it yourself.
Fixes #311
=> Relax URLs validation

config/config.go, config/config_test.go
Description should not be mandatory when defining a github endpoint.
Fixes #312
=> Relax description validation

cmd/garm-cli/cmd/enterprise.go, cmd/garm-cli/cmd/github_credentials.go, cmd/garm-cli/cmd/github_endpoints.go, cmd/garm-cli/cmd/organization.go, cmd/garm-cli/cmd/pool.go, cmd/garm-cli/cmd/repository.go, cmd/garm-cli/cmd/runner.go, database/sql/github.go, database/sql/util.go, params/params.go
This change adds a --long option to most commands and includes the CreateAt and UpdatedAt fields in the output.
Fixes #338
=> Add additional info when listing resources

apiserver/controllers/controllers.go, params/github.go
Ping events are no longer logged. Unknown events are now logged as Debug.
Fixes: #291
=> Update event logging

config/config.go, config/config_test.go, testdata/config.toml
In SQLite3 we may need to set a busy_timeout in the case of instances with high load. This change adds a knob that allows users to set a timeout if a database is locked for writing by another routine.
for details about the SQLIte3 option, see: https://www.sqlite.org/c3ref/busy_timeout.html
=> Add knob to tweak _busy_timeout

runner/pool/locking.go, runner/pool/pool.go
This change adds a backoff mechanism when deleting github runners. If the delete operation fails, we record the event and retry with a geometric progression of 1.5 starting from 5 seconds, which is the pool consolidation timeout.
=> Add a backoff mechanism when deleting runners

cache/credentials_cache.go, cache/entity_cache.go, cache/instance_cache.go, cache/util.go, cmd/garm-cli/cmd/github_credentials.go, params/interfaces.go, params/params.go, runner/github_credentials.go, workers/cache/cache.go, workers/scaleset/controller.go
This change adds a loop that keeps a cache of credentials rate limits as reported by the github API. The cache is updated every 30 seconds and is purely informational for the user.
This change also adds some caching improvements. Functions that return values from the cache as lists, will now sort by ID or creation date.
=> Add rate limit cache and fixes

.github/workflows/build-and-push.yml, .github/workflows/integration-tests.yml
When running as a scheduled task, we need to have default values for the reg and destination registry.
=> Use default values for ref and push to project

util/github/scalesets/runners.go
Make sure that the admin info is populated when calling GenerateJitRunnerConfig.
=> Ensure that admin token exists

database/sql/gitea.go, database/sql/gitea_test.go, database/sql/github.go, database/sql/github_test.go, database/sql/sql.go
This change allows users to remove the default github endpoint if no credentials are set on it.
A new protection is added on URLs of any endpoint that prevents their update if the endpoint has credentials set.
=> Make the default github endpoint mutable

runner/pool/common.go, test/integration/organizations_test.go, test/integration/repositories_test.go
=> Fix show webhooks.

cmd/garm-cli/cmd/enterprise.go, cmd/garm-cli/cmd/organization.go, cmd/garm-cli/cmd/pool.go, cmd/garm-cli/cmd/repository.go, cmd/garm-cli/cmd/scalesets.go, cmd/garm-cli/cmd/util.go
This change adds the ability to use the repo/org/enterprise names instead of UUID in most garm-cli commands, at the expense of an extra list API call, leveraging the recently added filter options.
[![asciicast](https://asciinema.org/a/pwCcPakk3aed31M2EgBVGU3cp.svg)](https://asciinema.org/a/pwCcPakk3aed31M2EgBVGU3cp)
=> Allow usage of friendly names in most commands

params/params.go
This change sets the github client http transport options to mirror those of the default transport from Go, with the addition of the TLSClientConfig.
=> Set http transport config

runner/pool/pool.go, workers/cache/tool_cache.go, workers/scaleset/scaleset.go, workers/scaleset/scaleset_listener.go
* time.NewTicker will panic if the duration is 0. Make it return early if duration is 0.
* Return a pre-closed channel in Wait() instead of nil. Ensures receiver will not block forever.
I need to create a common type for workers and de-duplicate some of the code, now that we have a clear pattern in how they are set up.
=> Fix sleepWithCancel and ensure closed channel

.github/workflows/build-and-push.yml, .github/workflows/trigger-manual.yml, .github/workflows/trigger-nightly.yml, Dockerfile
This P/R makes the workflows a bit cleaner and enable the build and push of 2 versions of garm images.
* The providers branch computation is done inside the Dockerfile now
* It automatically computes the latest (non pre-release) release of each provider before cloning
=> Refactor CI/CD builds

.github/workflows/build-and-push.yml
We need to pass the ref used in the workflow. If we supply a tag, we should just get that same tag. If we supply a branch, we should get the latest release from that branch.
=> Get the image tag from supplied ref

auth/instance_middleware.go, database/common/store.go, database/sql/instances.go, database/sql/instances_test.go, database/sql/jobs.go, runner/pool/pool.go, runner/runner.go
Although runner names are unique, we still have an ID on the model which is used as a primary key. We should allow using that ID to reference a runner in the API.
This change allows users to specify ID or runner name.
=> Allow referencing runners by ID

cmd/garm-cli/cmd/scalesets.go
Display all scalesets by default, similar to runners and pools.
=> Remove the --all flag for scalesets

database/sql/jobs.go, database/watcher/watcher_store_test.go
Previously, `garm` was not automatically creating new runners when new jobs appeared in Gitea. This was happening because the system was getting confused about job identification.
Here's what went wrong:
1.  **Saving Job Data:** When `garm` tried to save information about a new job into its database, it was accidentally using its own internal database ID for the job, instead of the unique job ID provided by Gitea. So,
the database record ended up with the wrong external ID.
2.  **Looking Up Jobs:** Later, when `garm` received updates about these jobs (like a webhook saying a job started), it tried to find the job in its database. But it was looking for the job using the unique ID from  
Gitea, and trying to match it against its _own internal database ID_. Since the IDs didn't match …
=> fix(jobs): Correctly handle workflow job IDs from webhooks

cmd/garm/main.go, websocket/websocket.go
* Shut down the web server first to prevent errors caused by clients trying to use functionality that has already been shut down, causing errors and potentially delaying the shutdown process.
* remove write timeout from the websocket Write() function.
=> Small fixes

database/sql/pools.go
Return more info when showing an entity pool. We should probably remove some of these API endpoints, as they duplicate a lot of functionality.
=> Preload more info for entity pools

workers/scaleset/controller.go, workers/scaleset/scaleset.go
Remove calls to github after creating a runner. It just adds overhead for very little benefit.
=> Some slight cleanup

internal/templates/userdata/windows_wrapper.tmpl, runner/metadata.go, runner/metadata_test.go
* The Windows userdata wrapper needs to run the real script with parameters that allow running a downloaded script and in a non-interactive way.
* The metadata endpoint to get the root CA bundle only worked for pools. This change fixes it for scale sets as well.
=> Fix Windows userdata wrapper and scale set metadata

apiserver/controllers/controllers.go
If the user sets "*" as a CORS origin, allow everything. Everything else needs to be an exact match.
=> Allow star CORS
